Repository uor-framework/uor-client-go, pull requests merged in 2022-07, with the labels that each got.

#39 build multi-arch binaries and multi-arch container
  Containerfile
  Makefile
Labels: enhancement

#48 build(deps): upgrades oras dep to resolve bug related to retagging ma…
  go.mod
  go.sum
Labels: bug

#44 Adds Schema design
  docs/design/schema.md
Labels: documentation
